######### Cadastro Tópico
POST http://127.0.0.1:3333/receita HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.7-iiD40U_cgDNfW4ABpFqm96m88iUrMeDYYxSW6_DYGLzdIXnIX4sAGB7n_Q

{
    "titulo": "torta salgada" ,
    "tipo": "para toda familia",
    "receita": "modo de preparo"
}

######### Listar todos os Tópico
GET http://127.0.0.1:3333/receita HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.7-iiD40U_cgDNfW4ABpFqm96m88iUrMeDYYxSW6_DYGLzdIXnIX4sAGB7n_Q


######### Listar Tópico específico
GET http://127.0.0.1:3333/receita/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.7-iiD40U_cgDNfW4ABpFqm96m88iUrMeDYYxSW6_DYGLzdIXnIX4sAGB7n_Q

######### Alterar Tópico
PUT http://127.0.0.1:3333/receita/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.7-iiD40U_cgDNfW4ABpFqm96m88iUrMeDYYxSW6_DYGLzdIXnIX4sAGB7n_Q

{
    "titulo": "bomba de chocolate",
    "tipo": "doce",
    "receita": "modo de preparo"

}

######### Apagar Tópico
DELETE http://127.0.0.1:3333/receita/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.7-iiD40U_cgDNfW4ABpFqm96m88iUrMeDYYxSW6_DYGLzdIXnIX4sAGB7n_Q
